# Generated by Django 5.1.3 on 2024-12-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('graduationYear', models.IntegerField()),
                ('enrollmentDetails', models.TextField()),
            ],
        ),
    ]
